[VAL-1] Implemented system users
valconsee-internship/videotecha-sanja pull request #1
Opened 2023-05-09 09:40 UTC by sanjadrinic

2023-05-09 09:41 UTC, sanjadrinic commented
![](https://github.trello.services/images/mini-trello-icon.png) [[VAL-1] Implement system users](https://trello.com/c/a9HPLrVi/15-val-1-implement-system-users)

2023-05-09 10:50 UTC, pantelicn requested changes

2023-05-09 10:50 UTC, pantelicn commented on src/main/java/com/project/videotecha/mapper/UserMapper.java
> +        }
can be shortened to `newUser.setUserType(UserType.valueOf(registrationData.getUserTypeName())`

2023-05-09 10:50 UTC, pantelicn commented on src/main/java/com/project/videotecha/service/impl/AuthenticationServiceImpl.java
> +        return userRepository.findByEmail(newUser.getEmail());
`save` method returns the created user, there is no need to make another call to the db by calling `findByEmail`.

2023-05-10 07:42 UTC, pantelicn approved these changes

2023-05-10 07:43 UTC, merged